# Generated by Django 3.1.3 on 2020-12-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20201224_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/%y'),
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
