# Generated by Django 3.1.3 on 2020-12-26 11:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='question',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
