# Generated by Django 3.1.3 on 2021-01-04 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_comment_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='liked',
        ),
    ]
