# Generated by Django 3.1.3 on 2021-01-05 07:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_auto_20210105_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='question_html',
            field=ckeditor.fields.RichTextField(editable=False),
        ),
    ]
