# Generated by Django 3.1.3 on 2021-03-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_auto_20210105_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
