# Generated by Django 3.1.3 on 2021-03-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_comment_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='like',
            field=models.BooleanField(default=True),
        ),
    ]
