# Generated by Django 3.1.3 on 2020-12-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='role',
            field=models.CharField(default='', max_length=20),
        ),
    ]
