# Generated by Django 3.1.3 on 2020-12-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='role',
        ),
        migrations.AddField(
            model_name='groupmember',
            name='role',
            field=models.CharField(default='', max_length=20),
        ),
    ]
