# Generated by Django 3.1.3 on 2020-12-29 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20201229_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmember',
            name='role',
        ),
    ]
