# Generated by Django 3.1.3 on 2021-01-04 11:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0004_remove_groupmember_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, through='groups.GroupMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
