# Generated by Django 3.2.5 on 2021-10-31 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_group_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='user',
            new_name='owner',
        ),
    ]
